{{- if and .Values.smtp.enabled .Values.smtp.persistence.enabled (not .Values.smtp.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crunchy-calendar.smtpServiceName" . }}-queue
  labels:
    {{- include "crunchy-calendar.labels" . | nindent 4 }}
    app.kubernetes.io/component: smtp
spec:
  accessModes:
    {{- toYaml .Values.smtp.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.smtp.persistence.size }}
  {{- with .Values.smtp.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
